### ISSUE TITLE
Modify the text size will go to invalid pages

### ISSUE THREAD

**Issue by evshary** [Adlink-ROS/rmt_web_devkit#15]
If I modify the text size of the webpage
![image](https://user-images.githubusercontent.com/456210/122885070-4fe36580-d371-11eb-98ff-e20803589f8a.png)
It'll show the following pages
![image](https://user-images.githubusercontent.com/456210/122885128-5d98eb00-d371-11eb-9f46-0fc5b46d5a20.png)
However, the text size is set successfully.

**Comment by QQting** [comment]
Fixed by removing this function: https://github.com/Adlink-ROS/rmt_web_devkit/commit/ddba3712a15aa08ecb4bfa7ac400827c6ce34997

**Comment by evshary** [comment]
Solved.
