### ISSUE TITLE
The user button does not work

### ISSUE THREAD

**Issue by evshary** [Adlink-ROS/rmt_web_devkit#16]
If we click the user button
![image](https://user-images.githubusercontent.com/456210/122888942-ec5b3700-d374-11eb-9010-874dc16e622b.png)
It'll show the page like this 
![image](https://user-images.githubusercontent.com/456210/122889105-14e33100-d375-11eb-8140-0c223da6df52.png)
The button can be removed if it does not have any function.

**Comment by QQting** [comment]
Fixed by removing this function: https://github.com/Adlink-ROS/rmt_web_devkit/commit/ddba3712a15aa08ecb4bfa7ac400827c6ce34997

**Comment by evshary** [comment]
Solved.
