### ISSUE TITLE
Some online agents are lost when refreshing monitor page

### ISSUE THREAD

**Issue by QQting** [Adlink-ROS/rmt_web_devkit#2]
Some online agents are lost when refreshing monitor page

For example, we launch two agents: 5566 and 5567. When the monitor page is refreshed, one of the agent disappears.

**Comment by QQting** [comment]
@H-HChen 
Could you help to check this issue?
Check whether it is the fontend or backend issue.
Thanks.

**Comment by QQting** [comment]
It seems to be RMT lib issue because the server got the message timeout warnings
:
![image](https://user-images.githubusercontent.com/320113/118910592-52f4cb80-b957-11eb-94a4-a66fcd6d2c28.png)

**Comment by QQting** [comment]
Wait for the parent issue to be fixed: https://github.com/Adlink-ROS/RMT/issues/26

**Comment by evshary** [comment]
The bug is fixed now, but now close and run agent frequently will cause ther server segmentation fault.
![Crash Image](https://user-images.githubusercontent.com/456210/119079143-2362c380-ba2a-11eb-9664-6f31a6166154.png)

**Comment by evshary** [comment]
The issue should be fixed now. Let's observe whether it'll happen again or not.

**Comment by evshary** [comment]
This issue should be fixed now.
